### PR TITLE
Remove MacOS binary data files, create .gitignore

### PR DESCRIPTION
**Pull request by smileycreations15**

### CODE REVIEW

**Comment by WorldLanguages** [comment]
Hi, thanks for the pull request! However I do not understand why you want to do this? Scratch Notifier runs directly on GitHub Pages inside of this repo, I don't think I can delete these files.

**Comment by smileycreations15** [comment]
@WorldLanguages This will prevent extra files in the repo. Even if the files come back, Git will ignore it.

**Comment by WorldLanguages** [comment]
Yeah? But I need these files to be served by GitHub pages... I can't delete them

**Comment by smileycreations15** [comment]
@WorldLanguages If you look the path, you will see that all of the path's of the deleted files start with __MACOSX/ . Do you need those files?

**Comment by WorldLanguages** [comment]
Yeah, all files have a purpose here!

**Pull request closed without merging**
